[package]
name = "slings"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
edition = "2018"

[dependencies]
slab = "0.4"
io-uring = { version = "0.4", features = ["concurrent", "unstable"] }
once_cell = "1.4"
libc = "0.2"
log = "0.4"
nix = "0.18"
concurrent-queue = "1.2"
async-task = "4.0"
futures-util = { version = "0.3", features = ["io"] }
parking_lot = "0.11"
rand = "0.7"
bytes = "0.5"
