[package]
name = "slings"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
edition = "2018"

[dependencies]
io-uring = { version = "0.5", features = ["unstable"] }
libc = "0.2"
log = "0.4"
concurrent-queue = "1.2"
async-task = "4.0"
parking_lot = "0.11"
bytes = "0.5"
scoped-tls = "1.0.0"
pin-project-lite = "0.2"
slab = "0.4"
