[package]
name = "cptio"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
edition = "2018"

[dependencies]
slab = "0.4"
io-uring = { version = "0.4", features = ["concurrent"] }
futures = "0.3"
once_cell = "1.4"
libc = "0.2"
