[package]
name = "slings"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
edition = "2018"

[dependencies]
io-uring = { version = "0.5", features = ["unstable"] }
async-task = "4.0"
parking_lot = "0.11"
scoped-tls = "1.0"
slab = "0.4"
libc = "0.2"
concurrent-queue = "1.2"
futures-util = { version = "0.3", features = ["io"] }
pin-project-lite = "0.2"
